# Generated by Django 3.2.8 on 2021-11-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_remove_fileupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='document',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
