# Generated by Django 3.2.8 on 2021-11-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_fileupload_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
