# Generated by Django 3.2.8 on 2021-11-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_alter_fileupload_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='is_password_protected',
            field=models.BooleanField(default=False),
        ),
    ]
