# Generated by Django 3.2.8 on 2021-11-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_fileupload_is_password_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
