# Generated by Django 3.2.8 on 2021-11-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_fileupload_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='count',
            new_name='page_count',
        ),
    ]
