# Generated by Django 3.2.8 on 2021-11-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_rename_count_fileupload_page_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='description',
        ),
    ]
