# Generated by Django 3.2.8 on 2021-12-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_auto_20211206_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='document',
            new_name='pdf_file',
        ),
    ]
