# Generated by Django 3.2.8 on 2021-12-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0012_rename_document_fileupload_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='read_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='read_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='read_password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
