# Generated by Django 3.2.8 on 2021-12-07 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0013_auto_20211206_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='read_email',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='read_password',
        ),
    ]
