# Generated by Django 3.2.8 on 2021-12-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0014_auto_20211207_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='read_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='read_gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='read_id',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
