# Generated by Django 3.2.8 on 2021-12-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0015_auto_20211207_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='read_id',
        ),
    ]
