# Generated by Django 3.2.8 on 2021-12-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0016_remove_fileupload_read_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='read_gender',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='read_room_no',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
