# Generated by Django 3.2.8 on 2021-12-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0017_auto_20211214_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='read_room_no',
            field=models.IntegerField(blank=True),
        ),
    ]
