# Generated by Django 3.2.8 on 2021-12-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0019_alter_fileupload_read_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='read_room_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
