# Generated by Django 3.2.8 on 2021-12-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0020_alter_fileupload_read_room_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='read_room_no',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='read_div',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
