# Generated by Django 3.2.8 on 2021-12-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0022_alter_fileupload_read_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='read_email',
            new_name='read_title',
        ),
    ]
