# Generated by Django 3.2.8 on 2021-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0023_rename_read_email_fileupload_read_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='xml_file',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
