# Generated by Django 3.2.8 on 2021-12-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0025_auto_20211214_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='read_xml',
            field=models.TextField(blank=True),
        ),
    ]
