# Generated by Django 3.2.8 on 2021-12-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0027_auto_20211215_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlfileupload',
            name='read_div',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='xmlfileupload',
            name='read_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='xmlfileupload',
            name='read_title',
            field=models.TextField(blank=True),
        ),
    ]
