# Generated by Django 3.2.8 on 2022-01-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0030_auto_20220103_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlfileupload',
            name='is_xml_file_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xmlfileupload',
            name='xml_parse_completed',
            field=models.BooleanField(default=False),
        ),
    ]
