# Generated by Django 3.2.8 on 2022-01-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0031_auto_20220103_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmlfileupload',
            name='read_div',
        ),
        migrations.AddField(
            model_name='xmlfileupload',
            name='xml_name_parse_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xmlfileupload',
            name='xml_title_parse_completed',
            field=models.BooleanField(default=False),
        ),
    ]
